version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            - 'MYSQL_ROOT_PASSWORD=123456'
            - 'MYSQL_DATABASE=wardrobe'
            - 'MYSQL_USER=graphql'
            - 'MYSQL_PASSWORD=123456'
        ports:
            - 8006:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - ./server/data:/docker-entrypoint-initdb.d
    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        links:
            - db
volumes:
    mysql_data: {} 